name: Create Release Archive

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(cat manifest.json | jq -r .version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Chrome version
        run: npm run build
        
      - name: Create Chrome ZIP
        run: |
          cd dist/chrome
          zip -r ../../chat-ext-chrome-${{ steps.get_version.outputs.version }}.zip ./*
          cd ../..

      - name: Build Firefox version
        run: npm run build -- --env firefox=true
        
      - name: Create Firefox ZIP
        run: |
          cd dist/firefox
          zip -r ../../chat-ext-firefox-${{ steps.get_version.outputs.version }}.zip ./*
          cd ../..

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Chrome Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chat-ext-chrome-${{ steps.get_version.outputs.version }}.zip
          asset_name: chat-ext-chrome-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./chat-ext-firefox-${{ steps.get_version.outputs.version }}.zip
          asset_name: chat-ext-firefox-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-archives
          path: |
            chat-ext-chrome-${{ steps.get_version.outputs.version }}.zip
            chat-ext-firefox-${{ steps.get_version.outputs.version }}.zip
